---
  - name: "install ndb packages"
    become: yes
    yum: name={{ item }} state=present
    with_items:
      - nbd
      - qemu-img
    tags:
      - ndbclient

  - name: "copy rac-nbd-client.init"
    become: yes
    template: src=rac-nbd-client.init.j2 dest=/usr/local/bin/rac-nbd-client.init owner=root group=root mode=0700
    tags:
      - ndbclient
      
  - name: "copy nbd-client.service"
    become: yes
    copy: src=rac-nbd-client.service dest=/etc/systemd/system/rac-nbd-client.service owner=root group=root mode=0700
    tags:
      - ndbclient

  - name: "daemon_reload"
    become: yes
    systemd: daemon_reload=yes
    ignore_errors: True
    tags:
      - ndbclient
      
  - name: "start_enable vxlan.service(Without NetworkManager)"
    become: yes
    service: name=rac-nbd-client.service state=started enabled=yes
    tags:
      - ndbclient