---
  - name: "install ndb packages"
    become: yes
    yum: name={{ item }} state=present  enablerepo=*
    with_items:
      - nbd
      - qemu-img
    tags:
      - nbdclient

  - name: "copy nbdtab"
    become: yes
    template: src="nbdtab.j2" dest="/etc/nbdtab" owner=root group=root mode=0700
    tags:
      - nbdclient
      
  - name: "copy racnbd@nbdX.service"
    become: yes
    copy: src="racnbd@.service" dest="/etc/systemd/system/racnbd@nbd{{ item }}.service" owner=root group=root mode=0700
    with_sequence: start=0 end=8
    tags:
      - nbdclient

  - name: "daemon_reload"
    become: yes
    systemd: daemon_reload=yes
    ignore_errors: True
    tags:
      - nbdclient
      
  - name: "start_enable racnbd@nbdX.service"
    become: yes
    service: name="racnbd@nbd{{ item }}.service" state=started enabled=yes
    when: nbd_local_container is not defined
    with_sequence: start=0 end=8
    tags:
      - nbdclient

  - name: "start_enable racnbd@nbdX.service for localcontainer1"
    become: yes
    service: name="racnbd@nbd{{ item }}.service" state=started enabled=yes
    with_sequence: start=0 end=2
    when: inventory_hostname == groups["dbserver"][0] and nbd_local_container is defined
    tags:
      - nbdclient

  - name: "start_enable racnbd@nbdX.service for localcontainer2"
    become: yes
    service: name="racnbd@nbd{{ item }}.service" state=started enabled=yes
    with_sequence: start=3 end=5
    when: inventory_hostname == groups["dbserver"][1] and nbd_local_container is defined
    tags:
      - nbdclient

  - name: "start_enable racnbd@nbdX.service for localcontainer3"
    become: yes
    service: name="racnbd@nbd{{ item }}.service" state=started enabled=yes
    with_sequence: start=6 end=8
    when: inventory_hostname == groups["dbserver"][2] and nbd_local_container is defined
    tags:
      - nbdclient