---
  - name: "install ndb packages"
    become: yes
    yum: name={{ item }} state=present 
    with_items:
      - nbd
      - qemu-img
    tags:
      - nbdclient

  - name: "copy nbdtab"
    become: yes
    template: src="nbdtab.j2" dest="/etc/nbdtab" owner=root group=root mode=0700
    when: ansible_distribution_version|int == 7
    tags:
      - nbdclient

  - name: "copy nbdtab"
    become: yes
    template: src="nbdtab6.j2" dest="/etc/nbdtab" owner=root group=root mode=0700
    when: ansible_distribution_version|int == 6
    tags:
      - nbdclient
      
  - name: "copy racnbd@nbdX.service"
    become: yes
    copy: src="racnbd@.service" dest="/etc/systemd/system/racnbd@nbd{{ item }}.service" owner=root group=root mode=0700
    with_sequence: start=0 end=8
    when: ansible_distribution_version|int == 7
    tags:
      - nbdclient

  - name: "daemon_reload"
    become: yes
    systemd: daemon_reload=yes
    ignore_errors: True
    tags:
      - nbdclient
      
  - name: "start_enable racnbd@nbdX.service"
    become: yes
    systemd: name="racnbd@nbd{{ item }}.service" state=started enabled=yes
    when: nbd_local_container is not defined and ansible_distribution_version|int == 7
    with_sequence: start=0 end=8
    tags:
      - nbdclient

  - name: "start_enable racnbd@nbdX.service for localcontainer1"
    become: yes
    systemd: name="racnbd@nbd{{ item }}.service" state=started enabled=yes
    with_sequence: start=0 end=2
    when: inventory_hostname == groups["dbserver"][0] and nbd_local_container is defined and ansible_distribution_version|int == 7
    tags:
      - nbdclient

  - name: "start_enable racnbd@nbdX.service for localcontainer2"
    become: yes
    systemd: name="racnbd@nbd{{ item }}.service" state=started enabled=yes
    with_sequence: start=3 end=5
    when: inventory_hostname == groups["dbserver"][1] and nbd_local_container is defined and ansible_distribution_version|int == 7
    tags:
      - nbdclient

  - name: "start_enable racnbd@nbdX.service for localcontainer3"
    become: yes
    systemd: name="racnbd@nbd{{ item }}.service" state=started enabled=yes
    with_sequence: start=6 end=8
    when: inventory_hostname == groups["dbserver"][2] and nbd_local_container is defined and ansible_distribution_version|int == 7
    tags:
      - nbdclient

  - name: "modprobe nbd"
    become: yes
    shell: "modprobe nbd"
    when: ansible_distribution_version|int == 6
    tags:
      - nbdclient

  - name: "start nbd-client"
    become: yes
    shell: "nbd-client {{ STORAGE_SERVER }}  {{ item.path }} -b 512 -N {{ item.name }};chmod 0660 {{ item.path }}; chown grid:asmadmin {{ item.path }}"
    when: nbd_local_container is not defined and ansible_distribution_version|int == 6
    with_items:
      - { name: 'vote', path: '/dev/nbd0' }
      - { name: 'data', path: '/dev/nbd1' }
      - { name: 'fra', path: '/dev/nbd2' }
    tags:
      - nbdclient

  - name: "start nbd-client"
    become: yes
    shell: "nbd-client {{ STORAGE_SERVER }}  {{ item.path }} -b 512 -N {{ item.name }};chmod 0660 {{ item.path }}; chown grid:asmadmin {{ item.path }}"
    when: nbd_local_container is defined and inventory_hostname == groups["dbserver"][0] and  ansible_distribution_version|int == 6
    with_items:
      - { name: 'vote', path: '/dev/nbd0' }
      - { name: 'data', path: '/dev/nbd1' }
      - { name: 'fra', path: '/dev/nbd2' }
    tags:
      - nbdclient




