---
  - name: "install nfs packages"
    become: yes
    yum: name={{ item }} state=present
    with_items:
      - nfs-utils
      - qemu-img
    tags:
      - nfsclient

  - name: "create oradata"
    become: yes
    file: path={{ item.path }} state=directory owner={{ item.name }} group=oinstall mode=0755
    with_items:
      - { name: 'grid', path: "{{ ORA_DATA }}" }
    when: storage_type == 'nfs'
    tags:
      - nfsclient


  - name: "restart rpcpind"
    become: yes
    shell: "chkconfig {{ item }} on;service  {{ item }} restart"
    when: ansible_distribution_version|int == 6
    with_items:
      - rpcbind
      - rpcidmapd
    tags:
      - nfsclient
      
  - name: "mount oradata"
    become: yes
    mount: name={{ ORA_DATA }} src="{{ STORAGE_SERVER }}:/" fstype=nfs opts="{{ NFS_OPS }}" state=mounted
    when: storage_type == 'nfs' and  ansible_distribution_version|int == 7
    tags:
      - nfsclient

  - name: "mount oradata"
    become: yes
    mount: name={{ ORA_DATA }} src="{{ STORAGE_SERVER }}:{{ STORAGE_ROOT }}" fstype=nfs opts="{{ NFS_OPS }}" state=mounted
    when: storage_type == 'nfs' and  ansible_distribution_version|int == 6
    tags:
      - nfsclient



  - name: "chown oradata"
    become: yes
    file: path={{ ORA_DATA }} state=directory owner=grid group=oinstall mode=0775
    tags:
      - nfsclient

  - name: "create asm device vote(qemu-img)"
    become: yes
    #shell: dd if=/dev/zero of={{ item.name }} bs=1M count={{ item.size }}
    shell: "qemu-img create -f raw -o size={{ item.size }}M {{ item.name }}"
    args:
      creates: "{{ item.name }}"
    when: inventory_hostname == groups["dbserver"][0] and DD_CMD is undefined and storage_type == "nfs"
    with_items:
      - { name: "{{ VOTE_DEV }}", size: "{{ VOTE_BASE_SIZE + VOTE_MULTI_SIZE * groups['dbserver'] | length  }}" }
      - { name: "{{ DATA_DEV }}", size: "{{ DATA_BASE_SIZE + DATA_MULTI_SIZE * groups['dbserver'] | length }}" }
      - { name: "{{ FRA_DEV }}", size: "{{ FRA_BASE_SIZE + FRA_MULTI_SIZE * groups['dbserver'] | length }}" }
    tags:
      - nfsclient

  - name: "create asm device vote(dd)"
    become: yes
    shell: dd if=/dev/zero of={{ item.name }} bs=1M count={{ item.size }}
    when: inventory_hostname == groups["dbserver"][0] and DD_CMD is defined and storage_type == "nfs"
    with_items:
      - { name: "{{ VOTE_DEV }}", size: "{{ VOTE_BASE_SIZE + VOTE_MULTI_SIZE * groups['dbserver'] | length  }}" }
      - { name: "{{ DATA_DEV }}", size: "{{ DATA_BASE_SIZE + DATA_MULTI_SIZE * groups['dbserver'] | length }}" }
      - { name: "{{ FRA_DEV }}", size: "{{ FRA_BASE_SIZE + FRA_MULTI_SIZE * groups['dbserver'] | length }}" }
    tags:
      - nfsclient

  - name: "chown oradata"
    become: yes
    file: path={{ item.name }} state=file owner=grid group=asmadmin mode=0660
    when: inventory_hostname == groups["dbserver"][0] and storage_type == "nfs"
    with_items:
      - { name: "{{ VOTE_DEV }}" }
      - { name: "{{ DATA_DEV }}" }
      - { name: "{{ FRA_DEV }}" }
    tags:
      - nfsclient

  - name: "enable remote-fs.target"
    become: yes
    systemd: name=remote-fs.target enabled=yes
    tags:
      - nfsclient
