---
  - name: "install ndb packages"
    become: yes
    yum: name={{ item }} state=present 
    with_items:
      - nbd
      - qemu-img
    tags:
      - nbdserver
      
  - name: "create nbd directory"
    become: yes
    file: path={{ ORA_DATA }} state=directory owner=root group=root mode=0755
    tags:
      - nbdserver

  - name: "create asm device vote(qemu-img)"
    become: yes
    #shell: dd if=/dev/zero of={{ item.name }} bs=1M count={{ item.size }}
    shell: "qemu-img create -f raw -o size={{ item.size }}M {{ item.name }}"
    args:
      creates: "{{ item.name }}"
    with_items:
      - { name: "{{ VOTE_DEV }}", size: "{{ VOTE_BASE_SIZE + VOTE_MULTI_SIZE * groups['dbserver'] | length  }}" }
      - { name: "{{ DATA_DEV }}", size: "{{ DATA_BASE_SIZE + DATA_MULTI_SIZE * groups['dbserver'] | length }}" }
      - { name: "{{ FRA_DEV }}", size: "{{ FRA_BASE_SIZE + FRA_MULTI_SIZE * groups['dbserver'] | length }}" }
    tags:
      - nbdserver

  - name: "create nbd directory"
    become: yes
    file: path=/etc/nbd-server state=directory owner=root group=root mode=0770
    tags:
      - nbdserver

  - name: "copy /etc/nbd-server/config"
    become: yes
    template: src=config.j2 dest=/etc/nbd-server/config owner=root group=root mode=0700
    tags:
      - nbdserver
      
  - name: "daemon_reload"
    become: yes
    systemd: daemon_reload=yes
    when: ansible_distribution_version|int == 7
    ignore_errors: True
    tags:
      - nbdserver
      
  - name: "start_enable nbd-server.service"
    become: yes
    systemd: name=nbd-server.service state=started enabled=yes
    when: ansible_distribution_version|int == 7
    tags:
      - nbdserver

  - name: "restart nbd"
    become: yes
    shell: "nbd-server"
    when: ansible_distribution_version|int == 6
    with_items:
      - nbd-server
    tags:
      - nbdserver