---
  - name: "install ndb packages"
    become: yes
    yum: name=ndb state=present
    tags:
      - ndbserver
      - ndbclient
      
  - name: "create nfs root directory"
    become: yes
    file: path={{ ORA_DATA }} state=directory owner=root group=root mode=0755
    tags:
      - nfsserver

  - name: "create exports"
    become: yes
    template: src=exports.j2 dest=/etc/exports owner=root group=root mode=0644
    tags:
       - nfsserver